# Generated by Django 5.0.2 on 2024-02-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_cliente_fecha_actualizacion_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='peso',
            field=models.IntegerField(),
        ),
    ]
