# Generated by Django 5.0.2 on 2024-02-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_paquete_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='idCliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='idTransportista',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='logistics.transportista'),
            preserve_default=False,
        ),
    ]
