# Generated by Django 5.0.2 on 2024-02-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_paquete_idcliente_paquete_idtransportista'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportista',
            name='disponible',
            field=models.CharField(default='Y', max_length=1),
            preserve_default=False,
        ),
    ]
