# Generated by Django 5.0.2 on 2024-02-18 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_transportista_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='idTransportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.transportista'),
        ),
    ]
